In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape(3,5)

In [3]:
type(arr) 

numpy.ndarray

In [4]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
arr.ndim # ilość wymiarów macierzy

2

In [6]:
arr.shape # kształt/rozmiar macierzy

(3, 5)

In [7]:
arr.size # wielkość/ilość komórek

15

In [8]:
arr.dtype # typ danych 

dtype('int64')

In [9]:
arr.itemsize # ile bajtów zajmuje pojedyńczy element

8

In [12]:
arr.data # adres pamięci

In [14]:
empty = np.empty((2,3)) # macierz z losowymi liczbami

In [15]:
empty

array([[6.01433264e+175, 6.93885958e+218, 5.56218858e+180],
       [3.94356143e+180, 8.60393211e-067, 1.73191337e+185]])

In [17]:
c = np.array([[1, 2], [3, 4]], dtype=complex) # macierz z liczbami zespolonymi

In [18]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [23]:
np.zeros((3,4)) # macierz wypełniona zerami, typ float64

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((2, 3, 4), dtype=np.int16) # macierz 3D wypełniona jedynkami, z zadeklarowanym typem danych 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
np.arange(10, 30, 5) # similar to range()

array([10, 15, 20, 25])

In [27]:
np.arange(0, 2, 0.3) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [28]:
from numpy import pi

In [35]:
np.linspace(0, 2*pi, 100) # wygenerowanie 100 liczb w danym zakresie w równych odstępach

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [42]:
np.random.random((2, 3)) # printing random array

array([[0.33356505, 0.28477585, 0.36240714],
       [0.29663525, 0.65739994, 0.41842581]])

In [43]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])


In [44]:
A*B

array([[2, 0],
       [0, 4]])

In [45]:
A@B

array([[5, 4],
       [3, 4]])

In [46]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [47]:
arr.sum(axis=0) # sum of each column

array([15, 18, 21, 24, 27])

In [48]:
arr.min(axis=1) # min from each row

array([ 0,  5, 10])

In [49]:
arr.cumsum(axis=1) # cumulative sum from each row

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])